### PR TITLE
Track all remote requests sent via AWS SDK

### PR DESCRIPTION
**Pull request by joehoyle**
When using the `HM\Platform\get_aws_sdk()`, we add a stats collector callback, so we can send all data of remote requests to AWS services to XRay.

I spend a long time, way way too long, trying to figure out how to wrap the AWS handlers / middleware via the client init params, but I just don't think it's possible to do that. Someone else way more experience with the AWS SDK may be able to do this, but I was not able to make good progress after several hours.

I ultimately had to go with using the Guzzle's `on_stats` callback. This is a lot lower level, we get the HTTP request and the HTTP response, but not hte higher level AWS Command object which would give us "real" access to the AWS Service etc. Turns that I was mostly able to work around that by digging what data we need out of the HTTP request and response though. This is certainly a huge improvement over what we have right now.

### CODE REVIEW

**Comment by nathanielks** [comment]
I followed up on the work I did the other day and came up with this gist: https://gist.github.com/nathanielks/b26eb5b7b50bc8d01ffe877a9e972251

This enables us to both have access to the Command and Request object, the Result object, and use AWS' middleware stack! The caveat is that we have to add to each service client's HandlerList to get access to all of this. Would we want to work this in at all?

**Comment by nathanielks** [comment]
For context, I saw they had a `mapResult` function on their [documentation page](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_handlers-and-middleware.html#mapresult) and modified that function to accomplish what I'm doing here.

**Comment by joehoyle** [comment]
@nathanielks the problem with this approach is the client needs to explicitly add the middleware to the handler list, which was the thing I was trying to avoid. Anyone using `HM\Platform\get_aws_sdk` would need to always make sure they added the middleware.

**Comment by nathanielks** [comment]
Indeed, it's rather annoying :confused: I suppose we could ascertain which action is being performed by the functions that are run around the request

**Comment by nathanielks** [comment]
Behold, all is not lost! I was reviewing `AWS\Sdk` and saw that it will merge the args passed to it with the args passed to the clients it creates. Because of this, we can pass the `handler` attribute which would be applied to all created clients. Handlers accept Command and Request objects and return a Result object. My thought is to copy the existing handler and simply modify it slightly so we can record what we need to record!

**Comment by joehoyle** [comment]
Yeah I had worked on that path for quite a while— but ultimately failed to
implement a handler that was able to properly wrap the default handler, as
one used by the ClientResolver is initiated with a bunch of internal class
state that I was not able to replicate in my own handler.

I certainly don’t want to stop trying, but I feel like maybe we should
review this pr as it stands, and if you are able to get it working via a
new handler then we upgrade to that.

**Comment by nathanielks** [comment]
> but ultimately failed to implement a handler that was able to properly wrap the default handler, as one used by the ClientResolver is initiated with a bunch of internal class state that I was not able to replicate in my own handler.

Damn, yeah, that's currently the hurdle I'm trying to cross presently

> I feel like maybe we should review this pr as it stands

Yup, sounds good. I'll get to that now.

**Comment by nathanielks** [comment]
Don't forget changelog!

**Comment by nathanielks** [comment]
DUDE. I can't believe I didn't think of this earlier. We can just extend `\Aws\Sdk` and override the `createClient` function to automatically add the middleware! 

Check out the latest iteration:
https://gist.github.com/nathanielks/b26eb5b7b50bc8d01ffe877a9e972251

**Comment by joehoyle** [comment]
Yeah I did think about that, I think it might be the best option. The sdk
class doesn’t allow any injection of other classes, so I don’t think
there’s an alternative to just replacing the root sdk class, and then
adding the middleware to every client that is created. I was a bit
reluctant as it’s a pretty big “swap”. I guess we could add a filter for
the sdk class name, and then have X-ray override that with its own sdk class

**Comment by nathanielks** [comment]
> I was a bit reluctant as it’s a pretty big “swap”

Eh, at least not in this specific implementation as we're not changing execution details, just adding an additional step. This is a pretty lite transformation, imo. I dig the idea of filtering the sdk class name!

**Pull request merged**
