### PR TITLE
Add support for Excimer instead of XHPRof

### PR DESCRIPTION
**Pull request by joehoyle**
Add support for Excimer as an alterntaive to XHProf, https://www.mediawiki.org/wiki/Excimer.

### CODE REVIEW

**Comment by rmccue** [comment]
@joehoyle needs refresh

**Comment by shadyvb** [comment]
Note that I rebased the PR to get a better view of changes, hence the force push.

**Review by roborourke — APPROVED** [review]
Looks like the debug code can be removed. Probably worth a follow up to fix the linter errors.

Could do a preview release of a new minor version bump to start using this now.

**Comment by shadyvb** [comment]
Agreed. Worth noting that excimer is available with PHP7 already, I've been testing the changes without upgrading to PHP8. So we can roll out a stable version but we need to monitor how it works in production.

**Pull request merged**
